"""empty message

Revision ID: 80791a40d25e
Revises: e25c42af3b47
Create Date: 2023-06-29 13:19:56.614087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80791a40d25e'
down_revision = 'e25c42af3b47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.Column('power', sa.Enum('管理员', '超级管理员'), nullable=False),
    sa.Column('phone', sa.String(length=11), nullable=True),
    sa.Column('address', sa.String(length=11), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin')
    # ### end Alembic commands ###
